# Generated by Django 3.1.7 on 2021-03-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='src',
            new_name='file',
        ),
    ]
